### ISSUE TITLE
HY链接不能运行；socks5不出配置连接

### ISSUE THREAD

**Issue by engama** [cmliu/socks5-for-serv00#2]
我的问题就是安装HY后，出的配置连接copy到V2RAY后不能运行，尝试重新安装结果显示已安装；还有就是socks5安装完后不出配置信息；
最后建议：能不能设置删除选项；版主给的删除命令，不清楚用户是指哪个？我的serv00的用户名和socks5的一样，删除会不会有影响？

**Comment by engama** [comment]
我安装的是天成的HY+socks5+保活的连接

**Comment by cmliu** [comment]
> 我安装的是天成的HY+socks5+保活的连接

你在我这说，他是看不到的，你要去他项目里反馈啊
